### PR TITLE
Create KMP algorithm

### PR DESCRIPTION
**Pull request by harshsharma-11**
kmp algo done
please review @abhaysinghr516

### CODE REVIEW

**Comment by abhaysinghr516** [comment]
It will be updated soon.

**Comment by harshsharma-11** [comment]
please review rest of the pull request

**Comment by harshsharma-11** [comment]
> It will be updated soon.
Screenshot (343)

i think ,it is not registerd yet i request you to please look what the problem is

**Comment by abhaysinghr516** [comment]
plz star the repo.

**Comment by harshsharma-11** [comment]
sure

**Pull request merged**
